feature/GENESIS-111-tax-rep-date-cust-address
OpusCapita/sales-invoice pull request #270
Opened 2020-11-26 19:46 UTC by ElaCzapiewska

2020-11-30 11:36 UTC, nczeranka requested changes
TaxReportingDate
* Is it really a field of type date? I understand it as an day or a month when the supplier has to report his taxes every year? Please clarify.
* Should the TaxReportingDate appear alway in the ui - for all countries? 
If yes, then we should add at lest the translations for the most customers - like Finnish and German. (I could imagine that at least the German ones will get confused and start asking questions.)

InvoiceAddress
* The global handling and validation on InvoiceAddress duplicate fields doesn't sound right.
Shouldn't we take this as the chance to setup validation on the subcomponent only?
* Should the manually added address not being maintainable as long as the SalesInvoice is not sent? (would require a flag in the schema to identify how the InvoiceAddress was filled.)
* What about old but active SalesInvoices without an ReceiverAddress? Now the sender is forced to enter an address. Is this as wanted?
Exactly in this case we have an error: On reediting an SalesInvoice with gaps in the InvoiceAddress, the Address editor is opened, but it closes directly on the first char/digit of the last empty field.

2020-11-30 11:36 UTC, nczeranka commented on src/client/components/SalesInvoice/SalesInvoiceConstraints.js
> +        }
I don't like the global validation on duplicated fields. But review the global comments and proceed based on the global decision on how to handle the InvoiceAddress.

2020-11-30 11:36 UTC, nczeranka commented on src/client/containers/SalesInvoiceEditor.js
> +            country: invoiceAddress && invoiceAddress.country,
Why, this duplication? Only for the validation?
Don't like to duplicate those fields. Check the global comment and proceed on decision there.

2020-11-30 11:36 UTC, nczeranka commented on src/client/containers/SalesInvoiceEditor.js
> +                        invoiceAddress: invoiceAddress || {street1: null, zipCode: null, city: null, country: null, show: true},
see comment above

2020-11-30 11:36 UTC, nczeranka commented on src/client/containers/SalesInvoiceEditor.js
> +
See comment about "first character of last empty field" in the global comment.

2020-11-30 11:36 UTC, nczeranka commented on src/client/containers/SalesInvoiceEditor.js
> +                                        {this.checkShowInvoiceAddressEditor() &&
see above

2020-11-30 11:36 UTC, nczeranka commented on src/client/containers/SalesInvoiceEditor.js
> +                                {this.checkShowInvoiceAddressEditor() &&
see above

2020-11-30 11:36 UTC, nczeranka commented on src/server/utils/invoiceDocDefinition.js
> +        invoiceHeaderItems.push([i18n.getMessage('Labels.taxReportingDate'), formatISODate(i18n, invoice.taxReportingDate)]);
Sounds for me like a sender specific field and I assume we should add it in the Supplier section of the report. Please clarify with Vesa.

2020-12-01 13:49 UTC, ElaCzapiewska commented on src/server/utils/invoiceDocDefinition.js
> +        invoiceHeaderItems.push([i18n.getMessage('Labels.taxReportingDate'), formatISODate(i18n, invoice.taxReportingDate)]);
ok, agreed with Vesa, moved into supplier section

2020-12-01 13:50 UTC, ElaCzapiewska commented on src/client/components/SalesInvoice/SalesInvoiceAddress.js
> +              })}
ok, indented

2020-12-01 19:13 UTC, ElaCzapiewska commented on src/client/components/SalesInvoice/SalesInvoiceAddress.js
> +              })}
and as to:
_- Should the manually added address not being maintainable as long as the SalesInvoice is not sent? (would require a flag in the schema to identify how the InvoiceAddress was filled.)_
I added new bool field to the schema (invoiceAddressIsManual), then invoice address fields are maintainable while the invoice is in draft status and only for manually entered address (where invoiceAddressIsManual is true)

_- What about old but active SalesInvoices without an ReceiverAddress? Now the sender is forced to enter an address. Is this as wanted?_
behavior changed, with the migration script all the existing invoices receive invoiceAddressIsManual=false, then such invoice will not ask for address completion (unless user switches customer -choose it again - then eventually missing address if still not exists in master data will be noticed and asked to be completed on invoice)

2020-12-01 19:17 UTC, ElaCzapiewska commented on src/client/components/SalesInvoice/SalesInvoiceConstraints.js
> +        }
duplication is removed, validation is performed directly on invoiceAddress fields

2020-12-01 19:17 UTC, ElaCzapiewska commented on src/client/containers/SalesInvoiceEditor.js
> +            country: invoiceAddress && invoiceAddress.country,
duplication is removed,  only invoiceAddress and its content is used

2020-12-01 19:20 UTC, ElaCzapiewska commented on src/client/containers/SalesInvoiceEditor.js
> +                        invoiceAddress: invoiceAddress || {street1: null, zipCode: null, city: null, country: null, show: true},
this is not duplication, this is just definition of the basic required structure of invoiceAddress if it does not exist in master data

2020-12-01 19:25 UTC, ElaCzapiewska commented on src/client/containers/SalesInvoiceEditor.js
> +
ok, solved with invoiceAddressIsManual field usage, condition is changed,
behavior also changed - with the migration script all the existing invoices receive invoiceAddressIsManual=false, then such invoice will not show address editor (unless user switches customer -choose it again - then eventually missing address, if still not exists in master data, will be noticed and asked to be completed on invoice)

2020-12-01 19:26 UTC, ElaCzapiewska commented on src/client/containers/SalesInvoiceEditor.js
> +                                        {this.checkShowInvoiceAddressEditor() &&
function is changed

2020-12-01 19:28 UTC, ElaCzapiewska commented on src/client/containers/SalesInvoiceEditor.js
> +                                {this.checkShowInvoiceAddressEditor() &&
function is changed

2020-12-02 15:01 UTC, nczeranka approved these changes

2020-12-02 15:07 UTC, nczeranka reviewed
Only thing you should check is: How to deal with the TaxReportingDate on CreditNotes?
* Should it be visible for CreditNotes?
* Should it be editable for CreditNotes?

2020-12-03 19:38 UTC, merged